
//Tente execultar! caso de erro trate a mensagem!
try {
    console.log(naoExisto)
} catch(err) {
    console.log('naoExisto nao existe')
}
